APT::FTPArchive::Release::Origin "qubes-buskill";
APT::FTPArchive::Release::Label "qubes-buskill";
APT::FTPArchive::Release::Suite "trixie";
APT::FTPArchive::Release::Codename "trixie";
APT::FTPArchive::Release::Architectures "amd64 all";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Qubes BusKill package repository";
