#!/usr/bin/env bash
set -euxo pipefail
################################################################################
# File:    buskill-try-selfdestruct-without-luks-wiping
# Purpose: Self-destruct trigger script for BusKill Kill Cord
#          (version for diagnosis, without wiping LUKS header)
#          For more info, see: https://buskill.in/
# Note   : This script will *not* execute unless it's passed the '--yes'
#          argument. Be sure to test this trigger before depending on it!
# Authors: Michael Altfield <michael@buskill.in>
# Co-Auth: Kamil Aronowski <kamil.aronowski@yahoo.com>
# Created: 2020-03-11
# Updated: 2026-09-30
# Version: 0.2
################################################################################
 
############
# SETTINGS #
############
 
WHICH="/usr/bin/which"
for util in cryptsetup ls cp mv ln mkdir mount cat grep echo awk head lsblk od chmod bash nohup sleep qvm-kill qvm-run poweroff chroot sync ldd xargs; do
  var="${util//-/_}"
  export ${var^^}=`${WHICH} ${util}` || echo "ERROR: Unable to find ${util}"
done

if [[ "$(${QVM_RUN} --no-gui --pass-io @USB_VM@ '[ -f /usr/bin/buskill-lock-interface-qubes.sh ] && echo OK')" != "OK" ]]; then
  ${ECHO} "ERROR: Unable to find script to lock all interface qubes"
  exit 1
fi
 
CHROOT_PATH='/dev/shm/buskill/chroot'
DIE_SCRIPT='/usr/bin/die.sh'
 
###########
# CONFIRM #
###########
 
# for safety, exit if this script is executed without a '--yes' argument
case "${@}" in
  *"--yes"*) ;;
  *) exit ;;
esac
if [ $? -ne 0 ]; then
  ${ECHO} "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING"
  ${ECHO} "================================================================================"
  ${ECHO} "WARNING: THIS IS EXPERIMENTAL SOFTWARE THAT IS DESIGNED TO CAUSE PERMANENT,  COMPLETE AND IRREVERSIBLE DATA LOSS!"
  ${ECHO} "================================================================================"
  ${ECHO} "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING"
  ${ECHO}
  ${ECHO} "cowardly refusing to execute without the '--yes' argument for your protection. If really you want to proceed with damaging your system, retry with the '--yes' argument"
  exit 1
fi
 
###########################
# (DELAYED) HARD SHUTDOWN #
###########################
 
# The most secure encrypted computer is an encrypted computer that is *off*
# This is our highest priority; initiate a hard-shutdown to occur in 1
# minute regardless of what happens later in this script
 
${NOHUP} ${SLEEP} 60 && ${ECHO} o > /proc/sysrq-trigger &
${NOHUP} ${SLEEP} 61 && ${POWEROFF} --poweroff --no-sync --no-wall --force &
${NOHUP} ${SLEEP} 62 && shutdown -h now &
 
###############
# LOCK SCREEN #
###############
 
# first action: lock the screen!
${QVM_RUN} --no-gui --pass-io @USB_VM@ '/usr/bin/buskill-lock-interface-qubes.sh' &
 
################
# KILL ALL VMs #
################
 
# doing this sooner will decrease the time needed to hard shutdown later
# See https://github.com/QubesOS/qubes-issues/issues/5887
${QVM_KILL} --all &
 
#######################
# WAIT ON DISK WRITES #
#######################
 
# clear write buffer to ensure headers overwrites are actually synced to disks
sync; echo 3 > /proc/sys/vm/drop_caches
 
#################
# CREATE CHROOT #
#################
 
# we have to create a ramfs chroot with cryptsetup, poweroff, and a few other
# basic depends for after we luksSuspend our rootfs from under our feet
 
for dir in proc sys dev pts bin lib64 lib/systemd usr/sbin usr/bin ; do
  ${MKDIR} -p "${CHROOT_PATH}/${dir}"
done
 
${MOUNT} -t proc none "${CHROOT_PATH}/proc"
${MOUNT} -t sysfs none "${CHROOT_PATH}/sys"
${MOUNT} -o bind /dev "${CHROOT_PATH}/dev"
${MOUNT} -o bind /dev/pts "${CHROOT_PATH}/dev/pts"
 
# copy-in our binaries and their depends
binaries="${BASH} ${CRYPTSETUP} ${ECHO} ${LS} ${NOHUP} ${SLEEP} ${XARGS} ${SYNC} ${POWEROFF}"
for binary in ${binaries}; do
  ${CP} -vf "${binary}" "${CHROOT_PATH}/${binary}"
  libs="$( ${LDD} "${binary}" | ${GREP} -Eo '/lib.*\.so(\.[0-9]*)*' )"
  for lib in ${libs}; do
    ${CP} -vf "${lib}" "${CHROOT_PATH}/${lib}"
  done
done
 
# fix around some libs and symlink issues
${MV} "${CHROOT_PATH}/lib" "${CHROOT_PATH}/usr/lib"
${LN} -s "usr/lib" "${CHROOT_PATH}/lib"
 
${CAT} << EOF > "${CHROOT_PATH}/${DIE_SCRIPT}"
#!${BASH}
 
# let's give ourselves 10 more seconds to wipe luks keys from RAM
${NOHUP} ${SLEEP} 10 && ${ECHO} o > /proc/sysrq-trigger &
${NOHUP} ${SLEEP} 11 && ${POWEROFF} --poweroff --no-sync --no-wall --force &
 
#################################
# WIPE DECRYPTION KEYS FROM RAM #
#################################
 
# suspend each currently-decrypted LUKS volume
${ECHO} "INFO: removing decryption keys from memory"
waits=''
for device in \$( ${LS} -1 "/dev/mapper" ); do
 
  ${ECHO} -e "\t\${device}";
  ${CRYPTSETUP} luksSuspend "\${device}" &
 
  waits="\${waits} $!"
 
done
${ECHO} "INFO: finished luksSuspend calls"
 
# xargs is our leading/trailing whitespace trim() function
waits=`${ECHO} "\${waits}" | ${XARGS}`
 
if [[ \${waits} ]]; then wait \${waits}; fi
${ECHO} "INFO: finished waiting"
 
# clear page caches in memory (again)
sync; echo 3 > /proc/sys/vm/drop_caches
${ECHO} "INFO: finished syncing"
 
#############################
# (IMMEDIATE) HARD SHUTDOWN #
#############################
${ECHO} "INFO: Powering Down"
 
# do whatever works; this is important.
${ECHO} o > /proc/sysrq-trigger &
${SLEEP} 1
${POWEROFF} --poweroff --no-sync --no-wall --force &
EOF
${CHMOD} +x "${CHROOT_PATH}/${DIE_SCRIPT}"
 
# finally, enter the chroot and call the above die.sh script inside it
${CHROOT} "${CHROOT_PATH}" "${DIE_SCRIPT}"
