#!/usr/bin/env bash
################################################################################
# File:    dom0:/usr/bin/buskill-set-trigger-to
# Purpose: Set the BusKill trigger for the USB qube and reload udev rules.
#          For more info, see: https://buskill.in/qubes-os/
# Created: 2026-09-05
# License: GNU GPLv3
################################################################################

set -euo pipefail

USB_VM='@USB_VM@'

BUSKILL_TRIGGER="$1"

case "${BUSKILL_TRIGGER}" in
  lock-screen)  ;;
  soft-shutdown)  ;;
  hard-reboot)  ;;
  self-destruct) ;;
  *)
    echo "Usage: $0 <BUSKILL_TRIGGER>"
    echo "Available triggers: lock-screen, soft-shutdown, hard-reboot, self-destruct"
    exit 1
    ;;
esac

qvm-features "${USB_VM}" vm-config.buskill-trigger "${BUSKILL_TRIGGER}"
qvm-run --no-gui --pass-io -u root "${USB_VM}" 'buskill-update-udev-rules && udevadm control --reload'
